/**
 * Server-side gacha pool data — source of truth for invocations.
 * Format: [nameFr, nameEn, slug, rarity, shinyRate]
 */
export type Rarity = 'common' | 'rare' | 'epic' | 'legendary'
type PoolEntry = [string, string, string, Rarity, number]

export interface GachaPokemon {
  nameFr: string
  nameEn: string
  slug: string
  rarity: Rarity
  shinyRate: number
}

export interface Banner {
  id: string
  nameFr: string
  nameEn: string
  generation: number
  costGold: number
  pool: GachaPokemon[]
}

function expand(entries: PoolEntry[]): GachaPokemon[] {
  return entries.map(([nameFr, nameEn, slug, rarity, shinyRate]) => ({
    nameFr, nameEn, slug, rarity, shinyRate,
  }))
}

export const RARITY_WEIGHTS: Record<Rarity, number> = {
  common: 60,
  rare: 34,
  epic: 5.5,
  legendary: 0.5,
}

// ═══ KANTO ═══
const KANTO: PoolEntry[] = [
  ['Rattata','Rattata','rattata','common',0.01],['Roucool','Pidgey','pidgey','common',0.01],
  ['Chenipan','Caterpie','caterpie','common',0.01],['Aspicot','Weedle','weedle','common',0.01],
  ['Nosferapti','Zubat','zubat','common',0.01],['Mystherbe','Oddish','oddish','common',0.01],
  ['Paras','Paras','paras','common',0.01],['Mimitoss','Venonat','venonat','common',0.01],
  ['Taupiqueur','Diglett','diglett','common',0.01],['Miaouss','Meowth','meowth','common',0.01],
  ['Tentacool','Tentacool','tentacool','common',0.01],['Racaillou','Geodude','geodude','common',0.01],
  ['Doduo','Doduo','doduo','common',0.01],['Kokiyas','Shellder','shellder','common',0.01],
  ['Soporifik','Drowzee','drowzee','common',0.01],['Krabby','Krabby','krabby','common',0.01],
  ['Voltorbe','Voltorb','voltorb','common',0.01],['Noeunoeuf','Exeggcute','exeggcute','common',0.01],
  ['Osselait','Cubone','cubone','common',0.01],['Smogo','Koffing','koffing','common',0.01],
  ['Poissirène','Goldeen','goldeen','common',0.01],['Stari','Staryu','staryu','common',0.01],
  ['Magicarpe','Magikarp','magikarp','common',0.01],['Piafabec','Spearow','spearow','common',0.01],
  ['Chétiflor','Bellsprout','bellsprout','common',0.01],['Pikachu','Pikachu','pikachu','common',0.01],
  ['Abo','Ekans','ekans','rare',0.02],['Sabelette','Sandshrew','sandshrew','rare',0.02],
  ['Nidoran♀','Nidoran♀','nidoranf','rare',0.02],['Nidoran♂','Nidoran♂','nidoranm','rare',0.02],
  ['Goupix','Vulpix','vulpix','rare',0.02],['Rondoudou','Jigglypuff','jigglypuff','rare',0.02],
  ['Mélofée','Clefairy','clefairy','rare',0.02],['Psykokwak','Psyduck','psyduck','rare',0.02],
  ['Férosinge','Mankey','mankey','rare',0.02],['Caninos','Growlithe','growlithe','rare',0.02],
  ['Ptitard','Poliwag','poliwag','rare',0.02],['Machoc','Machop','machop','rare',0.02],
  ['Ponyta','Ponyta','ponyta','rare',0.02],['Ramoloss','Slowpoke','slowpoke','rare',0.02],
  ['Magnéti','Magnemite','magnemite','rare',0.02],['Otaria','Seel','seel','rare',0.02],
  ['Tadmorv','Grimer','grimer','rare',0.02],['Rhinocorne','Rhyhorn','rhyhorn','rare',0.02],
  ['Hypotrempe','Horsea','horsea','rare',0.02],['Abra','Abra','abra','rare',0.02],
  ['Fantominus','Gastly','gastly','rare',0.02],['M. Mime','Mr. Mime','mrmime','rare',0.02],
  ['Lippoutou','Jynx','jynx','rare',0.02],['Élektek','Electabuzz','electabuzz','rare',0.02],
  ['Magmar','Magmar','magmar','rare',0.02],['Porygon','Porygon','porygon','rare',0.02],
  ['Amonita','Omanyte','omanyte','rare',0.02],['Kabuto','Kabuto','kabuto','rare',0.02],
  ['Onix','Onix','onix','rare',0.02],['Kicklee','Hitmonlee','hitmonlee','rare',0.02],
  ['Tygnon','Hitmonchan','hitmonchan','rare',0.02],['Excelangue','Lickitung','lickitung','rare',0.02],
  ['Saquedeneu','Tangela','tangela','rare',0.02],
  ['Bulbizarre','Bulbasaur','bulbasaur','epic',0.03],['Salamèche','Charmander','charmander','epic',0.03],
  ['Carapuce','Squirtle','squirtle','epic',0.03],['Minidraco','Dratini','dratini','epic',0.03],
  ['Évoli','Eevee','eevee','epic',0.03],['Lokhlass','Lapras','lapras','epic',0.03],
  ['Ronflex','Snorlax','snorlax','epic',0.03],['Insécateur','Scyther','scyther','epic',0.03],
  ['Scarabrute','Pinsir','pinsir','epic',0.03],['Tauros','Tauros','tauros','epic',0.03],
  ['Kangourex','Kangaskhan','kangaskhan','epic',0.03],['Leveinard','Chansey','chansey','epic',0.03],
  ['Ptéra','Aerodactyl','aerodactyl','epic',0.03],['Canarticho',"Farfetch'd",'farfetchd','epic',0.03],
  ['Métamorph','Ditto','ditto','epic',0.03],
  ['Artikodin','Articuno','articuno','legendary',0.05],['Électhor','Zapdos','zapdos','legendary',0.05],
  ['Sulfura','Moltres','moltres','legendary',0.05],['Mewtwo','Mewtwo','mewtwo','legendary',0.05],
  ['Mew','Mew','mew','legendary',0.05],
  ['Méga-Florizarre','Mega Venusaur','venusaur-mega','legendary',0.05],
  ['Méga-Dracaufeu X','Mega Charizard X','charizard-megax','legendary',0.05],
  ['Méga-Dracaufeu Y','Mega Charizard Y','charizard-megay','legendary',0.05],
  ['Méga-Tortank','Mega Blastoise','blastoise-mega','legendary',0.05],
  ['Méga-Dardargnan','Mega Beedrill','beedrill-mega','legendary',0.05],
  ['Méga-Roucarnage','Mega Pidgeot','pidgeot-mega','legendary',0.05],
  ['Méga-Alakazam','Mega Alakazam','alakazam-mega','legendary',0.05],
  ['Méga-Flagadoss','Mega Slowbro','slowbro-mega','legendary',0.05],
  ['Méga-Ectoplasma','Mega Gengar','gengar-mega','legendary',0.05],
  ['Méga-Kangourex','Mega Kangaskhan','kangaskhan-mega','legendary',0.05],
  ['Méga-Scarabrute','Mega Pinsir','pinsir-mega','legendary',0.05],
  ['Méga-Léviator','Mega Gyarados','gyarados-mega','legendary',0.05],
  ['Méga-Ptéra','Mega Aerodactyl','aerodactyl-mega','legendary',0.05],
  ['Méga-Mewtwo X','Mega Mewtwo X','mewtwo-megax','legendary',0.05],
  ['Méga-Mewtwo Y','Mega Mewtwo Y','mewtwo-megay','legendary',0.05],
]

// ═══ JOHTO ═══
const JOHTO: PoolEntry[] = [
  ['Fouinette','Sentret','sentret','common',0.01],['Hoothoot','Hoothoot','hoothoot','common',0.01],
  ['Coxy','Ledyba','ledyba','common',0.01],['Mimigal','Spinarak','spinarak','common',0.01],
  ['Granivol','Hoppip','hoppip','common',0.01],['Tournegrin','Sunkern','sunkern','common',0.01],
  ['Natu','Natu','natu','common',0.01],['Wattouat','Mareep','mareep','common',0.01],
  ['Marill','Marill','marill','common',0.01],['Axoloto','Wooper','wooper','common',0.01],
  ['Simularbre','Sudowoodo','sudowoodo','common',0.01],['Qwilfish','Qwilfish','qwilfish','common',0.01],
  ['Snubbull','Snubbull','snubbull','common',0.01],['Marcacrin','Swinub','swinub','common',0.01],
  ['Corayon','Corsola','corsola','common',0.01],['Rémoraid','Remoraid','remoraid','common',0.01],
  ['Cadoizo','Delibird','delibird','common',0.01],['Teddiursa','Teddiursa','teddiursa','common',0.01],
  ['Insolourdo','Dunsparce','dunsparce','common',0.01],['Loupio','Chinchou','chinchou','common',0.01],
  ['Capumain','Aipom','aipom','common',0.01],['Yanma','Yanma','yanma','common',0.01],
  ['Zarbi','Unown','unown','common',0.01],['Girafarig','Girafarig','girafarig','common',0.01],
  ['Pomdepik','Pineco','pineco','common',0.01],['Cerfrousse','Stantler','stantler','common',0.01],
  ['Phanpy','Phanpy','phanpy','common',0.01],['Pichu','Pichu','pichu','common',0.01],
  ['Mélo','Cleffa','cleffa','common',0.01],['Toudoudou','Igglybuff','igglybuff','common',0.01],
  ['Togepi','Togepi','togepi','common',0.01],['Démanta','Mantine','mantine','common',0.01],
  ['Limagma','Slugma','slugma','common',0.01],['Caratroc','Shuckle','shuckle','common',0.01],
  ['Feuforêve','Misdreavus','misdreavus','rare',0.02],['Cornèbre','Murkrow','murkrow','rare',0.02],
  ['Farfuret','Sneasel','sneasel','rare',0.02],['Magby','Magby','magby','rare',0.02],
  ['Élekid','Elekid','elekid','rare',0.02],['Lippouti','Smoochum','smoochum','rare',0.02],
  ['Debugant','Tyrogue','tyrogue','rare',0.02],['Airmure','Skarmory','skarmory','rare',0.02],
  ['Malosse','Houndour','houndour','rare',0.02],['Scorplane','Gligar','gligar','rare',0.02],
  ['Embrylex','Larvitar','larvitar','epic',0.03],
  ['Germignon','Chikorita','chikorita','epic',0.03],['Héricendre','Cyndaquil','cyndaquil','epic',0.03],
  ['Kaiminus','Totodile','totodile','epic',0.03],
  ['Écremeuh','Miltank','miltank','epic',0.03],['Scarhino','Heracross','heracross','epic',0.03],
  ['Queulorior','Smeargle','smeargle','epic',0.03],['Qulbutoké','Wobbuffet','wobbuffet','epic',0.03],
  ['Raikou','Raikou','raikou','legendary',0.05],['Entei','Entei','entei','legendary',0.05],
  ['Suicune','Suicune','suicune','legendary',0.05],['Lugia','Lugia','lugia','legendary',0.05],
  ['Ho-Oh','Ho-Oh','hooh','legendary',0.05],['Celebi','Celebi','celebi','legendary',0.05],
  ['Méga-Pharamp','Mega Ampharos','ampharos-mega','legendary',0.05],
  ['Méga-Steelix','Mega Steelix','steelix-mega','legendary',0.05],
  ['Méga-Cizayox','Mega Scizor','scizor-mega','legendary',0.05],
  ['Méga-Scarhino','Mega Heracross','heracross-mega','legendary',0.05],
  ['Méga-Démolosse','Mega Houndoom','houndoom-mega','legendary',0.05],
  ['Méga-Tyranocif','Mega Tyranitar','tyranitar-mega','legendary',0.05],
]

// ═══ HOENN ═══
const HOENN: PoolEntry[] = [
  ['Zigzaton','Zigzagoon','zigzagoon','common',0.01],['Medhyèna','Poochyena','poochyena','common',0.01],
  ['Nirondelle','Taillow','taillow','common',0.01],['Chuchmur','Whismur','whismur','common',0.01],
  ['Makuhita','Makuhita','makuhita','common',0.01],['Skitty','Skitty','skitty','common',0.01],
  ['Dynavolt','Electrike','electrike','common',0.01],['Chamallot','Numel','numel','common',0.01],
  ['Spoink','Spoink','spoink','common',0.01],['Spinda','Spinda','spinda','common',0.01],
  ['Kraknoix','Trapinch','trapinch','common',0.01],['Cacnea','Cacnea','cacnea','common',0.01],
  ['Wailmer','Wailmer','wailmer','common',0.01],['Carvanha','Carvanha','carvanha','common',0.01],
  ['Balbuto','Baltoy','baltoy','common',0.01],['Obalie','Spheal','spheal','common',0.01],
  ['Posipi','Plusle','plusle','common',0.01],['Négapi','Minun','minun','common',0.01],
  ['Chenipotte','Wurmple','wurmple','common',0.01],['Ningale','Nincada','nincada','common',0.01],
  ['Nénupiot','Lotad','lotad','common',0.01],['Grainipiot','Seedot','seedot','common',0.01],
  ['Goélise','Wingull','wingull','common',0.01],['Azurill','Azurill','azurill','common',0.01],
  ['Gloupti','Gulpin','gulpin','common',0.01],['Morphéo','Castform','castform','common',0.01],
  ['Balignon','Shroomish','shroomish','common',0.01],['Tarinor','Nosepass','nosepass','common',0.01],
  ['Meditikka','Meditite','meditite','common',0.01],['Muciole','Volbeat','volbeat','common',0.01],
  ['Lumivole','Illumise','illumise','common',0.01],['Tylton','Swablu','swablu','common',0.01],
  ['Mangriff','Zangoose','zangoose','common',0.01],['Seviper','Seviper','seviper','common',0.01],
  ['Séléroc','Lunatone','lunatone','common',0.01],['Solaroc','Solrock','solrock','common',0.01],
  ['Barloche','Barboach','barboach','common',0.01],['Écrapince','Corphish','corphish','common',0.01],
  ['Okéoké','Wynaut','wynaut','common',0.01],['Stalgamin','Snorunt','snorunt','common',0.01],
  ['Galekid','Aron','aron','common',0.01],['Arakdo','Surskit','surskit','common',0.01],
  ['Rosélia','Roselia','roselia','common',0.01],
  ['Tarsal','Ralts','ralts','rare',0.02],['Parecool','Slakoth','slakoth','rare',0.02],
  ['Ténéfix','Sableye','sableye','rare',0.02],['Mysdibule','Mawile','mawile','rare',0.02],
  ['Chartor','Torkoal','torkoal','rare',0.02],['Skelénox','Duskull','duskull','rare',0.02],
  ['Polichombr','Shuppet','shuppet','rare',0.02],['Tropius','Tropius','tropius','rare',0.02],
  ['Absol','Absol','absol','rare',0.02],['Draby','Bagon','bagon','rare',0.02],
  ['Terhal','Beldum','beldum','rare',0.02],['Barpau','Feebas','feebas','rare',0.02],
  ['Lilia','Lileep','lileep','rare',0.02],['Anorith','Anorith','anorith','rare',0.02],
  ['Kecleon','Kecleon','kecleon','epic',0.03],['Relicanth','Relicanth','relicanth','epic',0.03],
  ['Coquiperl','Clamperl','clamperl','epic',0.03],['Éoko','Chimecho','chimecho','epic',0.03],
  ['Lovdisc','Luvdisc','luvdisc','epic',0.03],
  ['Gobou','Mudkip','mudkip','epic',0.03],['Poussifeu','Torchic','torchic','epic',0.03],
  ['Arcko','Treecko','treecko','epic',0.03],
  ['Regirock','Regirock','regirock','legendary',0.05],['Regice','Regice','regice','legendary',0.05],
  ['Registeel','Registeel','registeel','legendary',0.05],['Latias','Latias','latias','legendary',0.05],
  ['Latios','Latios','latios','legendary',0.05],['Kyogre','Kyogre','kyogre','legendary',0.05],
  ['Groudon','Groudon','groudon','legendary',0.05],['Rayquaza','Rayquaza','rayquaza','legendary',0.05],
  ['Jirachi','Jirachi','jirachi','legendary',0.05],['Deoxys','Deoxys','deoxys','legendary',0.05],
  ['Méga-Jungko','Mega Sceptile','sceptile-mega','legendary',0.05],
  ['Méga-Braségali','Mega Blaziken','blaziken-mega','legendary',0.05],
  ['Méga-Laggron','Mega Swampert','swampert-mega','legendary',0.05],
  ['Méga-Gardevoir','Mega Gardevoir','gardevoir-mega','legendary',0.05],
  ['Méga-Ténéfix','Mega Sableye','sableye-mega','legendary',0.05],
  ['Méga-Mysdibule','Mega Mawile','mawile-mega','legendary',0.05],
  ['Méga-Galeking','Mega Aggron','aggron-mega','legendary',0.05],
  ['Méga-Charmina','Mega Medicham','medicham-mega','legendary',0.05],
  ['Méga-Élecsprint','Mega Manectric','manectric-mega','legendary',0.05],
  ['Méga-Sharpedo','Mega Sharpedo','sharpedo-mega','legendary',0.05],
  ['Méga-Camérupt','Mega Camerupt','camerupt-mega','legendary',0.05],
  ['Méga-Altaria','Mega Altaria','altaria-mega','legendary',0.05],
  ['Méga-Branette','Mega Banette','banette-mega','legendary',0.05],
  ['Méga-Absol','Mega Absol','absol-mega','legendary',0.05],
  ['Méga-Oniglali','Mega Glalie','glalie-mega','legendary',0.05],
  ['Méga-Drattak','Mega Salamence','salamence-mega','legendary',0.05],
  ['Méga-Métalosse','Mega Metagross','metagross-mega','legendary',0.05],
  ['Méga-Latias','Mega Latias','latias-mega','legendary',0.05],
  ['Méga-Latios','Mega Latios','latios-mega','legendary',0.05],
  ['Méga-Rayquaza','Mega Rayquaza','rayquaza-mega','legendary',0.05],
]

// ═══ SINNOH ═══
const SINNOH: PoolEntry[] = [
  ['Étourmi','Starly','starly','common',0.01],['Keunotor','Bidoof','bidoof','common',0.01],
  ['Crikzik','Kricketot','kricketot','common',0.01],['Rozbouton','Budew','budew','common',0.01],
  ['Cheniti','Burmy','burmy','common',0.01],['Apitrini','Combee','combee','common',0.01],
  ['Ceribou','Cherubi','cherubi','common',0.01],['Sancoki','Shellos','shellos','common',0.01],
  ['Baudrive','Drifloon','drifloon','common',0.01],['Laporeille','Buneary','buneary','common',0.01],
  ['Chaglam','Glameow','glameow','common',0.01],['Korillon','Chingling','chingling','common',0.01],
  ['Moufouette','Stunky','stunky','common',0.01],['Archéomire','Bronzor','bronzor','common',0.01],
  ['Manzaï','Bonsly','bonsly','common',0.01],['Mime Jr.','Mime Jr.','mimejr','common',0.01],
  ['Hippopotas','Hippopotas','hippopotas','common',0.01],['Rapion','Skorupi','skorupi','common',0.01],
  ['Cradopaud','Croagunk','croagunk','common',0.01],['Écayon','Finneon','finneon','common',0.01],
  ['Babimanta','Mantyke','mantyke','common',0.01],['Blizzi','Snover','snover','common',0.01],
  ['Lixy','Shinx','shinx','rare',0.02],['Pachirisu','Pachirisu','pachirisu','rare',0.02],
  ['Mustébouée','Buizel','buizel','rare',0.02],['Pijako','Chatot','chatot','rare',0.02],
  ['Vortente','Carnivine','carnivine','rare',0.02],['Motisma','Rotom','rotom','rare',0.02],
  ['Kranidos','Cranidos','cranidos','epic',0.03],['Dinoclier','Shieldon','shieldon','epic',0.03],
  ['Ptiravi','Happiny','happiny','epic',0.03],['Goinfrex','Munchlax','munchlax','epic',0.03],
  ['Riolu','Riolu','riolu','epic',0.03],['Spiritomb','Spiritomb','spiritomb','epic',0.03],
  ['Griknot','Gible','gible','epic',0.03],
  ['Tortipouss','Turtwig','turtwig','epic',0.03],['Ouisticram','Chimchar','chimchar','epic',0.03],
  ['Tiplouf','Piplup','piplup','epic',0.03],
  ['Créhelf','Uxie','uxie','legendary',0.05],['Créfollet','Mesprit','mesprit','legendary',0.05],
  ['Créfadet','Azelf','azelf','legendary',0.05],['Dialga','Dialga','dialga','legendary',0.05],
  ['Palkia','Palkia','palkia','legendary',0.05],['Heatran','Heatran','heatran','legendary',0.05],
  ['Regigigas','Regigigas','regigigas','legendary',0.05],['Giratina','Giratina','giratina','legendary',0.05],
  ['Cresselia','Cresselia','cresselia','legendary',0.05],['Phione','Phione','phione','legendary',0.05],
  ['Manaphy','Manaphy','manaphy','legendary',0.05],['Darkrai','Darkrai','darkrai','legendary',0.05],
  ['Shaymin','Shaymin','shaymin','legendary',0.05],['Arceus','Arceus','arceus','legendary',0.05],
  ['Méga-Lucario','Mega Lucario','lucario-mega','legendary',0.05],
  ['Méga-Carchacrok','Mega Garchomp','garchomp-mega','legendary',0.05],
  ['Méga-Lockpin','Mega Lopunny','lopunny-mega','legendary',0.05],
  ['Méga-Blizzaroi','Mega Abomasnow','abomasnow-mega','legendary',0.05],
  ['Méga-Gallame','Mega Gallade','gallade-mega','legendary',0.05],
]

// ═══ UNOVA ═══
const UNOVA: PoolEntry[] = [
  ['Ratentif','Patrat','patrat','common',0.01],['Ponchiot','Lillipup','lillipup','common',0.01],
  ['Chacripan','Purrloin','purrloin','common',0.01],['Feuillajou','Pansage','pansage','common',0.01],
  ['Flamajou','Pansear','pansear','common',0.01],['Flotajou','Panpour','panpour','common',0.01],
  ['Munna','Munna','munna','common',0.01],['Poichigeon','Pidove','pidove','common',0.01],
  ['Zébibron','Blitzle','blitzle','common',0.01],['Nodulithe','Roggenrola','roggenrola','common',0.01],
  ['Chovsourir','Woobat','woobat','common',0.01],['Nanméouïe','Audino','audino','common',0.01],
  ['Tritonde','Tympole','tympole','common',0.01],['Larveyette','Sewaddle','sewaddle','common',0.01],
  ['Venipatte','Venipede','venipede','common',0.01],['Doudouvet','Cottonee','cottonee','common',0.01],
  ['Chlorobule','Petilil','petilil','common',0.01],['Vivaldaim','Deerling','deerling','common',0.01],
  ['Trompignon','Foongus','foongus','common',0.01],['Miamiasme','Trubbish','trubbish','common',0.01],
  ['Crabicoque','Dwebble','dwebble','common',0.01],['Sorbébé','Vanillite','vanillite','common',0.01],
  ['Polarhume','Cubchoo','cubchoo','common',0.01],['Escargaume','Shelmet','shelmet','common',0.01],
  ['Carabing','Karrablast','karrablast','common',0.01],['Limonde','Stunfisk','stunfisk','common',0.01],
  ['Rototaupe','Drilbur','drilbur','rare',0.02],['Mascaïman','Sandile','sandile','rare',0.02],
  ['Darumarond','Darumaka','darumaka','rare',0.02],['Chinchidou','Minccino','minccino','rare',0.02],
  ['Scrutella','Gothita','gothita','rare',0.02],['Nucléos','Solosis','solosis','rare',0.02],
  ['Couaneton','Ducklett','ducklett','rare',0.02],['Emolga','Emolga','emolga','rare',0.02],
  ['Statitik','Joltik','joltik','rare',0.02],['Grindur','Ferroseed','ferroseed','rare',0.02],
  ['Tic','Klink','klink','rare',0.02],['Anchwatt','Tynamo','tynamo','rare',0.02],
  ['Lewsor','Elgyem','elgyem','rare',0.02],['Tutafeh','Yamask','yamask','rare',0.02],
  ['Viskuse','Frillish','frillish','rare',0.02],['Maracachi','Maractus','maractus','rare',0.02],
  ['Mamanbo','Alomomola','alomomola','rare',0.02],['Bargantua','Basculin','basculin','rare',0.02],
  ['Frison','Bouffalant','bouffalant','rare',0.02],
  ['Vipélierre','Snivy','snivy','epic',0.03],['Gruikui','Tepig','tepig','epic',0.03],
  ['Moustillon','Oshawott','oshawott','epic',0.03],['Charpenti','Timburr','timburr','epic',0.03],
  ['Baggiguane','Scraggy','scraggy','epic',0.03],['Zorua','Zorua','zorua','epic',0.03],
  ['Carapagos','Tirtouga','tirtouga','epic',0.03],['Arkéapti','Archen','archen','epic',0.03],
  ['Funécire','Litwick','litwick','epic',0.03],['Coupenotte','Axew','axew','epic',0.03],
  ['Kungfouine','Mienfoo','mienfoo','epic',0.03],['Scalpion','Pawniard','pawniard','epic',0.03],
  ['Furaiglon','Rufflet','rufflet','epic',0.03],['Vostourno','Vullaby','vullaby','epic',0.03],
  ['Gringolem','Golett','golett','epic',0.03],['Pyronille','Larvesta','larvesta','epic',0.03],
  ['Solochi','Deino','deino','epic',0.03],['Judokrak','Throh','throh','epic',0.03],
  ['Karaclée','Sawk','sawk','epic',0.03],['Cryptéro','Sigilyph','sigilyph','epic',0.03],
  ['Drakkarmin','Druddigon','druddigon','epic',0.03],['Aflamanoir','Heatmor','heatmor','epic',0.03],
  ['Fermite','Durant','durant','epic',0.03],['Hexagel','Cryogonal','cryogonal','epic',0.03],
  ['Victini','Victini','victini','legendary',0.05],['Cobaltium','Cobalion','cobalion','legendary',0.05],
  ['Terrakium','Terrakion','terrakion','legendary',0.05],['Viridium','Virizion','virizion','legendary',0.05],
  ['Boréas','Tornadus','tornadus','legendary',0.05],['Fulguris','Thundurus','thundurus','legendary',0.05],
  ['Reshiram','Reshiram','reshiram','legendary',0.05],['Zekrom','Zekrom','zekrom','legendary',0.05],
  ['Démétéros','Landorus','landorus','legendary',0.05],['Kyurem','Kyurem','kyurem','legendary',0.05],
  ['Keldeo','Keldeo','keldeo','legendary',0.05],['Meloetta','Meloetta','meloetta','legendary',0.05],
  ['Genesect','Genesect','genesect','legendary',0.05],
  ['Méga-Nanméouïe','Mega Audino','audino-mega','legendary',0.05],
]

// ═══ KALOS ═══
const KALOS: PoolEntry[] = [
  ['Sapereau','Bunnelby','bunnelby','common',0.01],['Passerouge','Fletchling','fletchling','common',0.01],
  ['Lépidonille','Scatterbug','scatterbug','common',0.01],['Hélionceau','Litleo','litleo','common',0.01],
  ['Flabébé','Flabébé','flabebe','common',0.01],['Cabriolaine','Skiddo','skiddo','common',0.01],
  ['Couafarel','Furfrou','furfrou','common',0.01],['Psystigri','Espurr','espurr','common',0.01],
  ['Fluvetin','Spritzee','spritzee','common',0.01],['Sucroquin','Swirlix','swirlix','common',0.01],
  ['Sepiatop','Inkay','inkay','common',0.01],['Opermine','Binacle','binacle','common',0.01],
  ['Venalgue','Skrelp','skrelp','common',0.01],['Flingouste','Clauncher','clauncher','common',0.01],
  ['Galvaran','Helioptile','helioptile','common',0.01],['Grelaçon','Bergmite','bergmite','common',0.01],
  ['Pitrouille','Pumpkaboo','pumpkaboo','common',0.01],['Brocélôme','Phantump','phantump','common',0.01],
  ['Pandespiègle','Pancham','pancham','rare',0.02],['Monorpale','Honedge','honedge','rare',0.02],
  ['Ptyranidur','Tyrunt','tyrunt','rare',0.02],['Amagara','Amaura','amaura','rare',0.02],
  ['Dedenne','Dedenne','dedenne','rare',0.02],['Strassie','Carbink','carbink','rare',0.02],
  ['Trousselin','Klefki','klefki','rare',0.02],['Brutalibré','Hawlucha','hawlucha','rare',0.02],
  ['Sonistrelle','Noibat','noibat','rare',0.02],
  ['Marisson','Chespin','chespin','epic',0.03],['Feunnec','Fennekin','fennekin','epic',0.03],
  ['Grenousse','Froakie','froakie','epic',0.03],['Mucuscule','Goomy','goomy','epic',0.03],
  ['Xerneas','Xerneas','xerneas','legendary',0.05],['Yveltal','Yveltal','yveltal','legendary',0.05],
  ['Zygarde','Zygarde','zygarde','legendary',0.05],['Diancie','Diancie','diancie','legendary',0.05],
  ['Hoopa','Hoopa','hoopa','legendary',0.05],['Volcanion','Volcanion','volcanion','legendary',0.05],
  ['Méga-Diancie','Mega Diancie','diancie-mega','legendary',0.05],
]

// ═══ ALOLA ═══
const ALOLA: PoolEntry[] = [
  ['Picassaut','Pikipek','pikipek','common',0.01],['Manglouton','Yungoos','yungoos','common',0.01],
  ['Larvibule','Grubbin','grubbin','common',0.01],['Plumeline','Oricorio','oricorio','common',0.01],
  ['Bombydou','Cutiefly','cutiefly','common',0.01],['Rocabot','Rockruff','rockruff','common',0.01],
  ['Froussardine','Wishiwashi','wishiwashi','common',0.01],['Tiboudet','Mudbray','mudbray','common',0.01],
  ['Mimantis','Fomantis','fomantis','common',0.01],['Spododo','Morelull','morelull','common',0.01],
  ['Nounourson','Stufful','stufful','common',0.01],['Croquine','Bounsweet','bounsweet','common',0.01],
  ['Bacabouh','Sandygast','sandygast','common',0.01],['Concombaffe','Pyukumuku','pyukumuku','common',0.01],
  ['Dodoala','Komala','komala','common',0.01],
  ['Rattata (Alola)','Rattata (Alola)','rattata-alola','common',0.01],
  ['Sabelette (Alola)','Sandshrew (Alola)','sandshrew-alola','common',0.01],
  ['Goupix (Alola)','Vulpix (Alola)','vulpix-alola','common',0.01],
  ['Taupiqueur (Alola)','Diglett (Alola)','diglett-alola','common',0.01],
  ['Miaouss (Alola)','Meowth (Alola)','meowth-alola','common',0.01],
  ['Racaillou (Alola)','Geodude (Alola)','geodude-alola','common',0.01],
  ['Tadmorv (Alola)','Grimer (Alola)','grimer-alola','common',0.01],
  ['Crabagarre','Crabrawler','crabrawler','rare',0.02],['Vorastérie','Mareanie','mareanie','rare',0.02],
  ['Araqua','Dewpider','dewpider','rare',0.02],['Tritox','Salandit','salandit','rare',0.02],
  ['Guérilande','Comfey','comfey','rare',0.02],['Gouroutan','Oranguru','oranguru','rare',0.02],
  ['Quartermac','Passimian','passimian','rare',0.02],['Sovkipou','Wimpod','wimpod','rare',0.02],
  ['Boumata','Turtonator','turtonator','rare',0.02],['Togedemaru','Togedemaru','togedemaru','rare',0.02],
  ['Mimiqui','Mimikyu','mimikyu','rare',0.02],['Denticrisse','Bruxish','bruxish','rare',0.02],
  ['Draïeul','Drampa','drampa','rare',0.02],['Sinistrail','Dhelmise','dhelmise','rare',0.02],
  ['Météno','Minior','minior','rare',0.02],
  ['Brindibou','Rowlet','rowlet','epic',0.03],['Flamiaou','Litten','litten','epic',0.03],
  ['Otaquin','Popplio','popplio','epic',0.03],['Bébécaille','Jangmo-o','jangmoo','epic',0.03],
  ['Type:0','Type: Null','typenull','epic',0.03],
  ['Tokorico','Tapu Koko','tapukoko','legendary',0.05],['Tokopiyon','Tapu Lele','tapulele','legendary',0.05],
  ['Tokotoro','Tapu Bulu','tapubulu','legendary',0.05],['Tokopisco','Tapu Fini','tapufini','legendary',0.05],
  ['Cosmog','Cosmog','cosmog','legendary',0.05],['Solgaleo','Solgaleo','solgaleo','legendary',0.05],
  ['Lunala','Lunala','lunala','legendary',0.05],['Necrozma','Necrozma','necrozma','legendary',0.05],
  ['Magearna','Magearna','magearna','legendary',0.05],['Marshadow','Marshadow','marshadow','legendary',0.05],
  ['Zeraora','Zeraora','zeraora','legendary',0.05],
  ['Zéroïd','Nihilego','nihilego','legendary',0.05],['Mouscoto','Buzzwole','buzzwole','legendary',0.05],
  ['Cancrelove','Pheromosa','pheromosa','legendary',0.05],['Câblifère','Xurkitree','xurkitree','legendary',0.05],
  ['Bamboiselle','Celesteela','celesteela','legendary',0.05],['Katagami','Kartana','kartana','legendary',0.05],
  ['Engloutyran','Guzzlord','guzzlord','legendary',0.05],['Vémini','Poipole','poipole','legendary',0.05],
  ['Ama-Ama','Stakataka','stakataka','legendary',0.05],['Pierroteknik','Blacephalon','blacephalon','legendary',0.05],
  ['Meltan','Meltan','meltan','legendary',0.05],
]

// ═══ GALAR ═══
const GALAR: PoolEntry[] = [
  ['Rongourmand','Skwovet','skwovet','common',0.01],['Minisange','Rookidee','rookidee','common',0.01],
  ['Larvadar','Blipbug','blipbug','common',0.01],['Goupilou','Nickit','nickit','common',0.01],
  ['Tournicoton','Gossifleur','gossifleur','common',0.01],['Moumouton','Wooloo','wooloo','common',0.01],
  ['Khélocrok','Chewtle','chewtle','common',0.01],['Voltoutou','Yamper','yamper','common',0.01],
  ['Charbi','Rolycoly','rolycoly','common',0.01],['Dunaja','Silicobra','silicobra','common',0.01],
  ['Embrochet','Arrokuda','arrokuda','common',0.01],['Toxizap','Toxel','toxel','common',0.01],
  ['Grillepattes','Sizzlipede','sizzlipede','common',0.01],['Poulpaf','Clobbopus','clobbopus','common',0.01],
  ['Bibichut','Hatenna','hatenna','common',0.01],['Grimalin','Impidimp','impidimp','common',0.01],
  ['Crèmy','Milcery','milcery','common',0.01],['Frissonille','Snom','snom','common',0.01],
  ['Charibari','Cufant','cufant','common',0.01],
  ['Miaouss (Galar)','Meowth (Galar)','meowth-galar','common',0.01],
  ['Ponyta (Galar)','Ponyta (Galar)','ponyta-galar','common',0.01],
  ['Ramoloss (Galar)','Slowpoke (Galar)','slowpoke-galar','common',0.01],
  ['Canarticho (Galar)',"Farfetch'd (Galar)",'farfetchd-galar','common',0.01],
  ['Corayon (Galar)','Corsola (Galar)','corsola-galar','common',0.01],
  ['Zigzaton (Galar)','Zigzagoon (Galar)','zigzagoon-galar','common',0.01],
  ['Darumarond (Galar)','Darumaka (Galar)','darumaka-galar','common',0.01],
  ['Tutafeh (Galar)','Yamask (Galar)','yamask-galar','common',0.01],
  ['Limonde (Galar)','Stunfisk (Galar)','stunfisk-galar','common',0.01],
  ['M. Mime (Galar)','Mr. Mime (Galar)','mrmime-galar','common',0.01],
  ['Caninos (Hisui)','Growlithe (Hisui)','growlithe-hisui','common',0.01],
  ['Voltorbe (Hisui)','Voltorb (Hisui)','voltorb-hisui','common',0.01],
  ['Qwilfish (Hisui)','Qwilfish (Hisui)','qwilfish-hisui','common',0.01],
  ['Farfuret (Hisui)','Sneasel (Hisui)','sneasel-hisui','common',0.01],
  ['Zorua (Hisui)','Zorua (Hisui)','zorua-hisui','common',0.01],
  ['Verpom','Applin','applin','rare',0.02],['Nigosier','Cramorant','cramorant','rare',0.02],
  ['Théffroi','Sinistea','sinistea','rare',0.02],['Hexadron','Falinks','falinks','rare',0.02],
  ['Wattapik','Pincurchin','pincurchin','rare',0.02],['Dolman','Stonjourner','stonjourner','rare',0.02],
  ['Bekaglaçon','Eiscue','eiscue','rare',0.02],['Wimessir','Indeedee','indeedee','rare',0.02],
  ['Morpeko','Morpeko','morpeko','rare',0.02],['Duralugon','Duraludon','duraludon','rare',0.02],
  ['Galvagon','Dracozolt','dracozolt','rare',0.02],['Galvagla','Arctozolt','arctozolt','rare',0.02],
  ['Hydragon','Dracovish','dracovish','rare',0.02],['Hydragla','Arctovish','arctovish','rare',0.02],
  ['Ouistempo','Grookey','grookey','epic',0.03],['Flambino','Scorbunny','scorbunny','epic',0.03],
  ['Larméléon','Sobble','sobble','epic',0.03],['Fantyrm','Dreepy','dreepy','epic',0.03],
  ['Zacian','Zacian','zacian','legendary',0.05],['Zamazenta','Zamazenta','zamazenta','legendary',0.05],
  ['Éthernatos','Eternatus','eternatus','legendary',0.05],['Wushours','Kubfu','kubfu','legendary',0.05],
  ['Zarude','Zarude','zarude','legendary',0.05],['Regieleki','Regieleki','regieleki','legendary',0.05],
  ['Regidrago','Regidrago','regidrago','legendary',0.05],['Blizzeval','Glastrier','glastrier','legendary',0.05],
  ['Spectreval','Spectrier','spectrier','legendary',0.05],['Sylveroy','Calyrex','calyrex','legendary',0.05],
  ['Amovénus','Enamorus','enamorus','legendary',0.05],
  ['Artikodin (Galar)','Articuno (Galar)','articuno-galar','legendary',0.05],
  ['Électhor (Galar)','Zapdos (Galar)','zapdos-galar','legendary',0.05],
  ['Sulfura (Galar)','Moltres (Galar)','moltres-galar','legendary',0.05],
]

// ═══ PALDEA ═══
const PALDEA: PoolEntry[] = [
  ['Gourmelet','Lechonk','lechonk','common',0.01],['Tissenboule','Tarountula','tarountula','common',0.01],
  ['Lilliterelle','Nymble','nymble','common',0.01],['Pohm','Pawmi','pawmi','common',0.01],
  ['Compagnol','Tandemaus','tandemaus','common',0.01],['Pâtachiot','Fidough','fidough','common',0.01],
  ['Olivini','Smoliv','smoliv','common',0.01],['Selutin','Nacli','nacli','common',0.01],
  ['Charbambin','Charcadet','charcadet','common',0.01],['Têtampoule','Tadbulb','tadbulb','common',0.01],
  ['Zapétrel','Wattrel','wattrel','common',0.01],['Grondogue','Maschiff','maschiff','common',0.01],
  ['Gribouraigne','Shroodle','shroodle','common',0.01],['Virovent','Bramblin','bramblin','common',0.01],
  ['Terracool','Toedscool','toedscool','common',0.01],['Pimito','Capsakid','capsakid','common',0.01],
  ['Léboulérou','Rellor','rellor','common',0.01],['Flotillon','Flittle','flittle','common',0.01],
  ['Forgerette','Tinkatink','tinkatink','common',0.01],['Taupikeau','Wiglett','wiglett','common',0.01],
  ['Dofin','Finizen','finizen','common',0.01],['Vrombi','Varoom','varoom','common',0.01],
  ['Germéclat','Glimmet','glimmet','common',0.01],['Toutombe','Greavard','greavard','common',0.01],
  ['Piétacé','Cetoddle','cetoddle','common',0.01],['Mordudor','Gimmighoul','gimmighoul','common',0.01],
  ['Axoloto (Paldea)','Wooper (Paldea)','wooper-paldea','common',0.01],
  ['Tapatoès','Squawkabilly','squawkabilly','rare',0.02],['Craparoi','Klawf','klawf','rare',0.02],
  ['Lestombaile','Bombirdier','bombirdier','rare',0.02],['Motorizard','Cyclizar','cyclizar','rare',0.02],
  ['Ferdeter','Orthworm','orthworm','rare',0.02],['Flamenroule','Flamigo','flamigo','rare',0.02],
  ['Délestin','Veluza','veluza','rare',0.02],['Oyacata','Dondozo','dondozo','rare',0.02],
  ['Nigirigon','Tatsugiri','tatsugiri','rare',0.02],
  ['Tauros (Paldea)','Tauros (Paldea)','tauros-paldea','rare',0.02],
  ['Tauros Flamboyant (Paldea)','Tauros Blaze (Paldea)','tauros-paldeablaze','rare',0.02],
  ['Tauros Aquatique (Paldea)','Tauros Aqua (Paldea)','tauros-paldeaaqua','rare',0.02],
  ['Poltchageist','Poltchageist','poltchageist','rare',0.02],
  ['Poussacha','Sprigatito','sprigatito','epic',0.03],['Chochodile','Fuecoco','fuecoco','epic',0.03],
  ['Coiffeton','Quaxly','quaxly','epic',0.03],['Frigodo','Frigibax','frigibax','epic',0.03],
  ['Chongjian','Wo-Chien','wochien','legendary',0.05],['Baojian','Chien-Pao','chienpao','legendary',0.05],
  ['Dinglu','Ting-Lu','tinglu','legendary',0.05],['Yuyu','Chi-Yu','chiyu','legendary',0.05],
  ['Fort-Ivoire','Great Tusk','greattusk','legendary',0.05],
  ['Hurle-Queue','Scream Tail','screamtail','legendary',0.05],
  ['Fongus-Furie','Brute Bonnet','brutebonnet','legendary',0.05],
  ['Flotte-Mèche','Flutter Mane','fluttermane','legendary',0.05],
  ['Rampe-Ailes','Slither Wing','slitherwing','legendary',0.05],
  ['Pelage-Sablé','Sandy Shocks','sandyshocks','legendary',0.05],
  ['Roue-de-Fer','Iron Treads','irontreads','legendary',0.05],
  ['Hotte-de-Fer','Iron Bundle','ironbundle','legendary',0.05],
  ['Paume-de-Fer','Iron Hands','ironhands','legendary',0.05],
  ['Tête-de-Fer','Iron Jugulis','ironjugulis','legendary',0.05],
  ['Mite-de-Fer','Iron Moth','ironmoth','legendary',0.05],
  ['Épine-de-Fer','Iron Thorns','ironthorns','legendary',0.05],
  ['Rugit-Lune','Roaring Moon','roaringmoon','legendary',0.05],
  ['Garde-de-Fer','Iron Valiant','ironvaliant','legendary',0.05],
  ['Koraidon','Koraidon','koraidon','legendary',0.05],['Miraidon','Miraidon','miraidon','legendary',0.05],
  ['Serpente-Eau','Walking Wake','walkingwake','legendary',0.05],
  ['Vert-de-Fer','Iron Leaves','ironleaves','legendary',0.05],
  ['Félicanis','Okidogi','okidogi','legendary',0.05],['Fortusimia','Munkidori','munkidori','legendary',0.05],
  ['Favianos','Fezandipiti','fezandipiti','legendary',0.05],['Ogerpon','Ogerpon','ogerpon','legendary',0.05],
  ['Feu-Perçant','Gouging Fire','gougingfire','legendary',0.05],
  ['Ire-Foudre','Raging Bolt','ragingbolt','legendary',0.05],
  ['Roc-de-Fer','Iron Boulder','ironboulder','legendary',0.05],
  ['Chef-de-Fer','Iron Crown','ironcrown','legendary',0.05],
  ['Térapagos','Terapagos','terapagos','legendary',0.05],['Pêchaminus','Pecharunt','pecharunt','legendary',0.05],
]

export const BANNERS: Banner[] = [
  { id: 'kanto', nameFr: 'Bannière Kanto', nameEn: 'Kanto Banner', generation: 1, costGold: 500, pool: expand(KANTO) },
  { id: 'johto', nameFr: 'Bannière Johto', nameEn: 'Johto Banner', generation: 2, costGold: 20000, pool: expand(JOHTO) },
  { id: 'hoenn', nameFr: 'Bannière Hoenn', nameEn: 'Hoenn Banner', generation: 3, costGold: 50000, pool: expand(HOENN) },
  { id: 'sinnoh', nameFr: 'Bannière Sinnoh', nameEn: 'Sinnoh Banner', generation: 4, costGold: 100000, pool: expand(SINNOH) },
  { id: 'unova', nameFr: 'Bannière Unys', nameEn: 'Unova Banner', generation: 5, costGold: 200000, pool: expand(UNOVA) },
  { id: 'kalos', nameFr: 'Bannière Kalos', nameEn: 'Kalos Banner', generation: 6, costGold: 290000, pool: expand(KALOS) },
  { id: 'alola', nameFr: 'Bannière Alola', nameEn: 'Alola Banner', generation: 7, costGold: 390000, pool: expand(ALOLA) },
  { id: 'galar', nameFr: 'Bannière Galar', nameEn: 'Galar Banner', generation: 8, costGold: 510000, pool: expand(GALAR) },
  { id: 'paldea', nameFr: 'Bannière Paldea', nameEn: 'Paldea Banner', generation: 9, costGold: 650000, pool: expand(PALDEA) },
]
